### ISSUE TITLE
Open at login should be optional

### ISSUE THREAD

**Issue by zeke** [zeit/now-desktop#152]
I know that preferences are the devil™, but I find it odd that Now.app is in my menu bar on every restart and there's no (obvious) way to disable that behavior.

**Comment by backspaces** [comment]
Just remove it from your account's startup apps in system preferences.

**Comment by leo** [comment]
@zeke Maybe we should rewrite it so that it only gets added to the startup apps once at the startup so that you can remove it from there afterwards?

**Comment by leo** [comment]
✔️

**Comment by zeke** [comment]
Only setting this at first run is definitely an improvement, but I still feel like an in-app option to toggle the login setting would be the polite thing to do (even though users can disable it in system preferences).

**Comment by leo** [comment]
@zeke Coming (private, because big update)... Hihi 😊

**Comment by zeke** [comment]
🍰
