### ISSUE TITLE
New flow for installing CLI

### ISSUE THREAD

**Issue by leo** [zeit/now-desktop#177]
Instead of installing a binary with node enclosed, we should install node first and then trigger the installation of the "now" package globally. Here are the advantages of this mechanism:

- Rather than cluttering our user's system with multiple instances of node laying around, there will only be a single one.
- We're supporting the spread of node across various environments, because the user will be able to use the instance of node we've installed later if he wants to.
- At the moment, we're creating a new enclosed binary for each platform and then we're attaching it to the respective GitHub release (in addition to the npm release). Just like the npm release, this binary needs to be tested separately, which (+ the workflow itself) takes a lot of time. This could easily be automated using Travis. But we could also get rid of it completely, by only doing the npm release.
- The app is currently downloading the latest release from GitHub (that's also where we're checking for updates). GitHub is not a package manager and therefore has some problems regarding rate limiting for downloads, which makes many of them fail... This will also be solved!
- We're currently experiencing a lot of failures when it comes to setting the correct permissions on the binary, having enough rights to do so and finding out which ones are the perfect ones to set.
- The user will be able to easily set the location where the binaries are located by telling the npm configuration about it. We can stop determining where WE think it should be located the best.
- All of the closed issues you're seeing down there will be fixed as well...

I'm working on a programmatic npm client which abstracts things like updates and the global installation of packages through the CLI.

### What Needs to Be Done

- [ ] Implement installation, updates and version checks for global packages in [npm-client](https://github.com/zeit/npm-client).
- [ ] Adjust CLI section to let user know that we'll download node + npm.
- [ ] When the user clicks the "Install" button, the app needs to check if node is already installed and up-to-date. If it's not, we'll download and install it from the site (comes with npm).
- [ ] The app should use [npm-client](https://github.com/zeit/npm-client) to install the CLI and check if it's the latest version every 5 minutes.

**Comment by jamo** [comment]
I'm a little bit worried that installing node and including it to path would cause too much confusion among our users. 
Since the node installation would essentially be required in two cases:
- User has really old node (like 0.1.x)
- User doesn't have node at all / has a super unconventional installation

For both of the cases above, adding a new node to path will increase the amount of confusion and likely breaks something.
Also installing/requiring installation of node for non-node developers to use `now` isn't optimal.

> Why would I need to install programming language X and it's package managers to use a single project - while we can just have those in medium sized binaries

So maybe we could make the `now` installation and update a bit harder for us but nicer for our users, by splitting it into two cases:
- `npm i -g now` for all users who have up-to-date/new enough node installed.
- use the enclosed `now` others  (people who have no node, or too old installation)

**Comment by fmiras** [comment]
What if we ask to the user if he wants node (with a checkbox maybe) and if the user don't want node we uninstall it again after installing now?

**Comment by balupton** [comment]
You could use https://github.com/bevry/safeps to access the user's global node and npm installations.

So you could do:

```
safeps.spawn(['npm', 'install', '-g', 'now'], function (error, stdout, stderr, status, signal) {})
```

Then follow it up with:

```
safeps.spawn(['now'], function (error, stdout, stderr, status, signal) {})
```

http://rawgit.com/bevry/safeps/master/docs/#getExecPath can also be used to check for existence, (by default safeps.spawn calls this anyway), it takes into account weird setups and whatnot

**Comment by jamo** [comment]
I'm not sure if I can see the benefits of`safeps` based on a quick glipmse over the docs... 🤔 

Anyways IMHO now-desktop shouldn't become yet another node installer... but either `npm install -g` or just get the binary...

**Comment by leo** [comment]
After taking some time to think about this, I don't really think it's a good anymore. Let's see what the future holds and how many people would like to see this happen!
