### ISSUE TITLE
The application "Now" can't be opened.

### ISSUE THREAD

**Issue by joelburget** [zeit/now-desktop#208]
I got this on my computer (actually, both of them), launching `now` from spotlight (though double clicking the application from finder has the same result). Downloading a new `Now` from the website fixed the issue for me the first time I ran into this. `which now` points to a `yarn install`ed script (`/usr/local/Cellar/node/6.3.1/bin/now -> ../../../../../../Users/joel/.yarn-config/global/node_modules/.bin/now`), which allows me to deploy, but may have something to do with the issue?

![screen shot 2016-12-07 at 10 15 27 am](https://cloud.githubusercontent.com/assets/310981/20973302/2de63772-bc66-11e6-905e-37afb6c72ac7.png)

**Comment by nriesco** [comment]
I had the same issue. I didn't restart my computer but after removing the application (`rm -r /Applications/Now.app`) and downloading it again (or copy the original one) it worked. It only happened once.

**Comment by leo** [comment]
Should work from now on! Could have happened with any other application as well.

**Comment by timmywil** [comment]
This just happened to me. It's never happened with other apps, but I can confirm downloading again fixes it.

**Comment by eezing** [comment]
Just happened to me. rm -r & re-download fixed it.

**Comment by phtoussaint** [comment]
Same here, and same fix.
