### ISSUE TITLE
Stuck at "Downloading the binary..."

### ISSUE THREAD

**Issue by stephenhowells** [zeit/now-desktop#216]
When installing the Now desktop app I get to the screen where it attempts to download the binary. It seems unable to get past this step. It hovers around 13% CPU but isn't using any bandwidth. The app isn't frozen it just isn't installing the binary. I'm on macOS 10.12.1. This is the screen it's sticking on:

![screen shot 2016-12-14 at 8 40 07 am](https://cloud.githubusercontent.com/assets/436173/21188720/8165c9bc-c1d9-11e6-9ec2-7f0bf57e6c96.png)

**Comment by stephenhowells** [comment]
For anybody else who experienced this issue, after a while I just quit the app and installed `now` from npm. I relaunched the desktop app and it works as expected. 🙂

**Comment by leo** [comment]
@stephenhowells Can you please `npm uninstall now -g` and try to install the CLI again from Now Desktop? It should work now.

**Comment by johannesvorster** [comment]
I'm experiencing the same issue. I'm using a Windows 10 machine.

Please let me know if you need something else?

**Comment by leo** [comment]
Fix coming!
