### ISSUE TITLE
Now.app conflict with now-cli: npm path problem

### ISSUE THREAD

**Issue by backspaces** [zeit/now-desktop#217]
My npm dir is not /usr/local, it instead uses these instructions to put it in my home directory:
https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory

This appears to not work well with now and Now.app .. I get two global now installs. Slack chats:
https://zeit-community.slack.com/archives/now/p1481742564002296
https://zeit-community.slack.com/archives/now/p1481754784002344

Leading to:
albinekb [12:25 PM]  @backspaces: make an issue and I'll look at making a pr for that in the weekend :)

.. so here it is.  Key point is the which -a suggested by @jamo:
```
which -a now
/Users/owen/npm/bin/now
/usr/local/bin/now
```

Using a simple script  shows:
```
 Directory /Users/owen/npm/bin
now        now.old.1
 Directory /usr/local/bin
now
 Directory /usr/bin
 Directory /bin
 Directory /usr/sbin
 Directory /sbin
 Directory /Users/owen/bin
```
The key symptom is that `now ls` constantly nags to upgrade, `npm install -g now`, but after the upgrade, I still get the nags! This lead to the discovery of two now binaries.

**Comment by backspaces** [comment]
A bit more info: I got a nag to update, so ran `npm install -g now`. I then ran `now -v` for both binaries. Works as expected, the /usr/local version is stale while ~/npm version is updated. What's odd is just running `now -v` appears to run the /usr/local version even tho it is second in the PATH/which -a listing!
```
MBP13|~[766]: npm install -g now
/Users/owen/npm/bin/now -> /Users/owen/npm/lib/node_modules/now/build/bin/now
/Users/owen/npm/lib
└── now@0.37.0 

MBP13|~[767]: /Users/owen/npm/bin/now -v
𝚫 now 0.37.0

MBP13|~[768]: /usr/local/bin/now -v
𝚫 now 0.35.0
> UPDATE NEEDED Current: 0.35.0 – Latest 0.37.0 (released 7h ago)
> Run `npm install -g now` to update

MBP13|~[769]: now -v
𝚫 now 0.35.0
> UPDATE NEEDED Current: 0.35.0 – Latest 0.37.0 (released 7h ago)
> Run `npm install -g now` to update

MBP13|~[770]: which -a now
/Users/owen/npm/bin/now
/usr/local/bin/now

MBP13|~[771]: echo $PATH
/Users/owen/npm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/owen/bin
```

**Comment by leo** [comment]
@backspaces Can you please remove the npm binary using `npm uninstall now -g`? After that, please run `which now` and if it still outputs a path, delete that one as well.

Once you're done with deleting all instances of the binary, please make sure Now Desktop is at >= 0.4.5 on your device (if it somehow isn't, re-download it).

After all of that, please install the binary from the CLI section in the tutorial that shows up when you sign in the first time into Now Desktop. You can also open the tutorial from the "About" window (see the links at the bottom).

**Comment by backspaces** [comment]
Thanks, very clear.

.. But using the tutorial to install now-cli still places it in /usr/local.


MBP13|~[1012]: which -a now

/usr/local/bin/now


I guess that's OK as long as I don't also use npm .. which will put it in ~/
npm/bin.

Somehow the install does not catch my .npmrc

MBP13|~[1015]: more .npmrc
prefix=${HOME}/npm

**Comment by leo** [comment]
@backspaces Respecting the global `.npmrc` is a great idea! Can you add an issue for that?
