### ISSUE TITLE
Respect the global .npmrc install directory

### ISSUE THREAD

**Issue by backspaces** [zeit/now-desktop#226]
If the user specifies a directory for npm global installs in their .npmrc, the Now.app should install the now-cli executable into that dir rather than in /usr/local:
https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory

**Comment by leo** [comment]
I just thought about this for a bit and came to the conclusion that it's not really a good idea because we're trying to be independent from node (that's why the app exists). 😊

**Comment by backspaces** [comment]
I hope this is a joke. A simple npm configuration should be universal, right? So all my global installs, other than now, go to ~/npm .. now goes to /usr/local/bin/now.

OTOH, if this is only an issue for the Now desktop, then fine, the user has the option of just using that and I'm fairly sure that would put now in ~/npm. One could argue Now should manage the cli as it pleases.
