### ISSUE TITLE
Make alias option?

### ISSUE THREAD

**Issue by stursby** [zeit/now-desktop#227]
I would love it if there was a `Make Alias` option from my list of deployments from the GUI here:

![image](https://cloud.githubusercontent.com/assets/527849/21462680/700672e6-c924-11e6-9549-d46cc766fa0f.png)

**Comment by balupton** [comment]
Here's a proposed UI from the tweet https://twitter.com/aranajhonny/status/817817833392504833
 
![c1l47ljwgaagwkx jpg-large](https://cloud.githubusercontent.com/assets/61148/21966846/5511d68e-dbb6-11e6-853f-fb01a57a1973.jpeg)

Seems like a window is better for this than a menubar - as that menubar requires a lot of keeping your mouse curser perfectly on the menu to prevent the menu from hiding

**Comment by leo** [comment]
Coming very soon! 😉

**Comment by siddharthkp** [comment]
@leo 👋
