### ISSUE TITLE
Support for nvm

### ISSUE THREAD

**Issue by aexmachina** [zeit/now-desktop#232]
I'm using nvm, but Now Desktop only updates the system Node. How can I get it to update nvm-installed instances of Node.js?

**Comment by leo** [comment]
It doesn't update the system Node at all. The version of the CLI that we're installing comes with Node enclosed, so it works even on systems without Node.

**Comment by aexmachina** [comment]
I see. Okay that's not really what many developers would want. I just want to avoid having to run npm install -g now@latest all the time
