### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by abelovic** [zeit/now-desktop#243]
How do I use this in windows?

If I take one of the samples:

1. npm install
2. npm run dev

I check it out in the browser and everything looks good so now I want to deploy. I choose deploy from the now desktop icon in my tray and select the folder (for the example i.e. with-apollo). I get the error:

"Your project is xxx MB bigger than the currently allowed maximum size of 5MB"

There is not really any code in these samples... I am assuming it is including the node_modules folder? Can I exclude this or am I doing this all wrong? Do I have to delete the node_modules folder first? Do I have to build? If so when I run npm run build I don't see anything created?

If I try to run now directly from the command line instead (after installing now via npm i now -g) I get the following:

"const {resolve}" = require('path')

SyntaxError: Unexpected token {
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.module._extensions..js (module.js:416:10)
at Module.;oad (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:139:18)
at node.js:990:3

Tried this on 2 different windows 10 machines. One with Node v4.7.2 and the other with v7.4.0 and both gave me the same results.

**Comment by leo** [comment]
Should work now!
