### ISSUE TITLE
Now CLI failed upgrade

### ISSUE THREAD

**Issue by andyeskridge** [zeit/now-desktop#245]
Now Desktop Version: 0.6.1
OS: Windows 10

The `now-cli.exe ` is on my path and was working a few days ago at least. This morning when I went to try out the new `now.json` feature I went to check to see if Now Desktop updated my `now` command. 

It seems like it definitely changed the command, but something happened in the process. ~~(This could also just be an issue on the actual Now CLI repo.)~~ I just tested by downloading the 4.0.0 release from the now-cli repo and that is working correctly. 

![image](https://cloud.githubusercontent.com/assets/507452/22397362/57ce8f60-e535-11e6-8d28-3e8aa99697b2.png)

**Comment by andyeskridge** [comment]
A workaround for this issue:

1. Delete the `now.exe` from %APPDATA%]Local\now-cli
2. Go to the About page and start the Tutorial again
3. Install the command in the Tutorial

**Comment by leo** [comment]
@andyeskridge Have you received the latest update? 4.0.1

**Comment by andyeskridge** [comment]
Yes I did, but only because I manually removed the bad now-cli version.

**Comment by leo** [comment]
@andyeskridge Once in the beginning? Did the auto update for 4.0.1 work?

**Comment by andyeskridge** [comment]
Whoops! Sorry for being unclear. 

Yes I only had to remove the broken version once in the beginning. Once I was on 4.0.0 the now-desktop was able to upgrade to 4.0.1

**Comment by leo** [comment]
Ahhh, okay. Then it should work fine from here! It probably downloaded a broken version because of a network issue or sth like that...
