### ISSUE TITLE
Ability to reinstall now CLI

### ISSUE THREAD

**Issue by sedubois** [zeit/now-desktop#247]
Now proposed me the first time I installed it, whether I'd like the CLI too, which I accepted. But then I screwed up my installation I believe as I thought I was uninstalling the npm version. Anyway, now I don't have the `now` CLI any more but I don't know how to ask Now-Desktop to install it again for me. My only workaround is to install it manually from NPM, but I suppose that version won't get automatic updates.

BTW I need the CLI because the desktop still has too many limitations (e.g says my project is too big to be deployed).

**Comment by leo** [comment]
Click on "About" in the menu and then on "Tutorial" at the bottom... 😊

**Comment by sedubois** [comment]
Thanks. The location isn't very clear... I think a menu entry would be helpful 😊

Also, it took 5 seconds for the tutorial to open, it felt like the application was stuck.

Also, when downloading the binary, there's no progress indication at all. No way to know if the download is stuck or if it's just slow because of the network.

**Comment by leo** [comment]
Yep. We're working on a overhauled version internally!
