### ISSUE TITLE
Freeze on osx

### ISSUE THREAD

**Issue by phtoussaint** [zeit/now-desktop#256]
Hi!
The app froze twice when entering the email. I'm not familiar with electron so I don't know how I could provide some helpful to work with.
I could try to reproduce.

**Comment by panphora** [comment]
I just got the same bug. It sends the verification email, but a message pops up saying it couldn't generate the token. So, I can't get past the last step. I'm on macOS Sierra 10.12.3

**Comment by leo** [comment]
@phtoussaint @panphora Is this still happening?

**Comment by panphora** [comment]
I'm no longer seeing this. 

However, I am getting a weird JSON error when my Mac starts up.

**Comment by panphora** [comment]
I got it a day or two ago and then quit the app. I can't reboot right now, but I'll report back if it comes up again.

**Comment by leo** [comment]
Okay, thanks! 🙏
