### ISSUE TITLE
Feature Request: Deploying static webstie

### ISSUE THREAD

**Issue by italoacasas** [zeit/now-desktop#272]
The app right now is [looking for a package.json](https://github.com/zeit/now-desktop/blob/370cc03c95f52a2231ff1d248001faea796c6fce/app/main/actions/deploy.js#L125) but that is not a requirement for the cli. 

<img width="268" alt="capture" src="https://cloud.githubusercontent.com/assets/6354455/24211051/4c60aa82-0f01-11e7-9431-c127043aa772.PNG">

**Comment by leo** [comment]
This already works! You just need to use the "Share" option.
