### ISSUE TITLE
The desktop app keeps opening new copies of itself

### ISSUE THREAD

**Issue by HenrikWL** [zeit/now-desktop#290]
Updated the desktop app to 1.0.0 the other day, and it keeps opening copies of itself. Faster than I can close them, I have to do killall -9 now from command line in order to clear it up.

I'm on macOS 10.12.4

**Comment by leo** [comment]
Are the processes called "Now Helper" or something similar?

**Comment by HenrikWL** [comment]
No, the output of ps ax shows steadily increasing numbers of "now -v". Also, the macOS toolbar fills up with the black triangles, and the context menu for it keeps popping up and grabbing focus.

**Comment by jamo** [comment]
User report related to probably the same issue:
<img width="814" alt="screen shot 2017-04-06 at 20 22 26" src="https://cloud.githubusercontent.com/assets/1354151/24784346/d02c495a-1b06-11e7-89c4-35df9999d7dd.png">

**Comment by HenrikWL** [comment]
Not saying it can't be related, but I don't see this cache duplication in my case. It's the actual running process that keeps respawning multiple copies of itself.

**Comment by mtford90** [comment]
I'm getting this too. The only way to stop it is to restart my computer & quit it as soon as it opens... I've ended up just removing it entirely.

**Comment by jamo** [comment]
To help to troubleshoot this, could you please provide some additional information:
- os and os version
- whether it has downloaded lots of updates to the cache dir (see screenshot above - in Finder Go -> Go to Folder and type in `Library/Cache` and look for folders starting with `co.zeit.now`)
- Now.app version (open finder in /Applications find Now.app, right-click and select `Get Info` (or cmd+i). It should show version number alongside other information)

and any other information which might be helpful. this seem to be somewhat rare issue...

**Comment by tomouchuu** [comment]
Was getting same issue on now.app 1.0.0 so updated to latest version (as of now 1.2.1) by downloading and installing from the dmg over the original version. Still getting the issue, info as below:

* Mac OS X, 10.12.4
* Library/Caches/co.zeit.now.Shipit size 29kb
* Library/Caches/co.zeit.now size 311kb
* Now.app version 1.2.1
* now --version 2.0.2
* node --version 7.7.3

Image below of issue and get infos on those folders and now.app (sorry for the japanese text)
<img width="1680" alt="2017-04-17 18 13 03" src="https://cloud.githubusercontent.com/assets/1489059/25097294/e21bf7e4-239b-11e7-8038-0b0796be3eb5.png">

Installed in /Applications and symlinked to /Users/me/Applications

I just redownloaded the dmg and installed after an app cleaner remove the previous application and getting same issue.

**Comment by leo** [comment]
Can you please remove:

- `Library/Caches/co.zeit.now`
- `Library/Caches/co.zeit.now.Shipit`
- `Library/Application\ Support/Now`

And then try downloading the latest version of the app (1.2.2, just released) and see if it works this time? If possible, please also check without symlinking it - just open it from the "Downloads" directory (because the symlinking might as well be the issue).

**Comment by tomouchuu** [comment]
That worked for me 👍 
Thanks leo!

**Comment by leo** [comment]
I see! Now can you check if it's still working when symlinked?

**Comment by tomouchuu** [comment]
Symlinked is now fine  ¯\_(ツ)_/¯

**Comment by leo** [comment]
Sweet! 👌
