### ISSUE TITLE
Fix hot code reloading for renderer

### ISSUE THREAD

**Issue by leo** [zeit/now-desktop#293]
<img width="936" alt="screen shot 2017-04-11 at 15 33 20" src="https://cloud.githubusercontent.com/assets/6170607/24911721/42556020-1ecc-11e7-9c45-ebe9889b6c02.png">

@MarshallOfSound It looks like the above is what breaks auto reloading

**Comment by joecohens** [comment]
I think this is Chromium blocking the `next:` protocol because it doesn't trust it. Maybe having an `http:` protocol for development would be nice and then just change it for the build to the personal one.

**Comment by leo** [comment]
I think we can tell the window do treat it as secure using Electron's API

**Comment by MarshallOfSound** [comment]
@joecohens @leo That error is sent from electron-routes and is the equivalent of a 404 I believe.  Will need to look into this more when i get the chance.

The rebdererPreload function from electron-routes adds next as a trusted / safe protocol so that shouldn't be an issue (all other next requests work)

**Comment by leo** [comment]
Can we add the protocol as trusted earlier? Like when creating the window? Or maybe set the `webSecurity` property to `false`?

**Comment by MarshallOfSound** [comment]
@leo If you add preload scripts to the windows and in the preload script call that function that's as early as we can go 👍

**Comment by leo** [comment]
If that fixed our problem - sure...?

**Comment by leo** [comment]
Would be lovely if this could be fixed inside electron-routes, because then I could set up a pretty blog post about using Next.js in combination with Electron. Until then, I'm going to use a native HTTP server for development and electron-routes for production.
