### ISSUE TITLE
Deploying 'Getting Started' example from Next.js is 22.73mb bigger than allowed 5mb

### ISSUE THREAD

**Issue by inspiraller** [zeit/now-desktop#296]
Considering the Getting started steps for next.js are ridiculously small, why would this be bigger than the 248kb that is the size of the app.js bundle? Let alone 27.73mb?

**Comment by albinekb** [comment]
you should only need 2 files and 1 folder to deploy the getting started, total of only a couple KB
```
/package.json
/pages/index.js
```

package.json:
```json
{
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "latest",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
}```

**Comment by albinekb** [comment]
Yep, then that's definitely a bug. Could you zip up your directory and put a link here so we can try to reproduce? 

Thanks

**Comment by inspiraller** [comment]
**I've added it to github for reproducing**
https://github.com/inspiraller/nextjs_not_working

**Comment by albinekb** [comment]
Looks like this function https://github.com/zeit/now-desktop/blob/master/main/actions/deploy.js#L41

is not following the rules that deploy does (eg. looking at .gitignore)
