### ISSUE TITLE
Installing now-cli via now-desktop doesn't update existing now-cli

### ISSUE THREAD

**Issue by lukechilds** [zeit/now-desktop#300]
I already had now-cli installed via npm. Installing the latest version with now-desktop didn't actually give me the latest version via `now` until I manually ran `npm uninstall -g now`.

**Comment by leo** [comment]
These are two different binaries. One comes from Now Desktop and contains Node (to work on devices without Node) and the other one is from npm. We're working on communicating this in a better way!

**Comment by lukechilds** [comment]
Maybe it would be better to uninstall now if it's already installed via npm. Or if that's a bit too invasive maybe check for the existence of npm now and alert the user to uninstall via npm to be able to use the latest version.

**Comment by leo** [comment]
Correct - that's the plan: Alerting the user.
