### ISSUE TITLE
Stuck at email verification step 

### ISSUE THREAD

**Issue by raybesiga** [zeit/now-desktop#302]
Hi Team

I installed Now about a week ago and received a verification team. However, when i clicked on it about 2 hours after I received it, I got the following error message:

```
{"err":{"code":"authentication_error","url":"https://zeit.co/errors/authentication_error","message":"Invalid verification token"}}
```
Despite having the right code on both desktop and email. How do i resolve this?

**Comment by leo** [comment]
Is it working now? 😊  Also where did you get the error?
