### ISSUE TITLE
No CLI tool installed

### ISSUE THREAD

**Issue by Sequoia** [zeit/now-desktop#304]
1. I installed via `npm` first
2. registered via login
3. removed the NPM version
4. Installed desktop version

## Expected
Now desktop added a cli binary

## Actual
```
$ which now
now not found
```

## platform
* OSX
* using NVM

**Comment by Sequoia** [comment]
where is this "install CLI button"? Am I missing it?

**Comment by rauchg** [comment]
@Sequoia go to About > Tutorial and head to the third step.

**Comment by Sequoia** [comment]
Whewee that button is hidden but good!! 😸 

Thanks, and possibly consider making "install CLI client" a top level drop-down menu option.

**Comment by rauchg** [comment]
Yeah we're definitely making it more prominent for v2. cc @evilrabbit

**Comment by rauchg** [comment]
Thank you!
