### ISSUE TITLE
Pkg: Error reading from file

### ISSUE THREAD

**Issue by Sequoia** [zeit/now-desktop#306]
The now CLI just completely broke on me :(

```
$ now
Pkg: Error reading from file.

$ now --version
Pkg: Error reading from file.

$ now --help
Pkg: Error reading from file.

$ which now
/usr/local/bin/now
```

![About Now](https://i.imgur.com/uhrnwHi.png)

My workflow has ground to a complete halt :( what do.

**Comment by leo** [comment]
Just tried it - works for me. Can you manually run this please:

```bash
rm -rf `which now`
```

**Comment by Sequoia** [comment]
Thanks. Any idea what caused this?

**Comment by leo** [comment]
@Sequoia Have you managed to fix it by reinstalling it?

**Comment by Sequoia** [comment]
Yes, thank you.
