### ISSUE TITLE
How to uninstall Now from menu bar

### ISSUE THREAD

**Issue by jonathanwmaddison** [zeit/now-desktop#308]
I uninstalled the Now.app yet I still have a Now icon on my mac Menu bar which gives me notifications. It would be helpful to have clear instructions on how to remove Now desktop app completely.

**Comment by leo** [comment]
Click on it and then "Quit Now".

**Comment by jonathanwmaddison** [comment]
I see, I had to register my email address. Ideally, "quit now" would be accessible without having to enter in any data or register.

**Comment by leo** [comment]
It is! Simply right click on the icon.

**Comment by jonathanwmaddison** [comment]
On my mac, I tried this but it would bring up the Now UI(not the menu where
quit now is an option). It only allowed me to right click and quit after I
filled in my email.

**Comment by leo** [comment]
Okay. A fix is coming with the next (currently secret) release! 😋

**Comment by jonathanwmaddison** [comment]
Awesome, thanks 😎
