### ISSUE TITLE
Don't auto open on login

### ISSUE THREAD

**Issue by bnjmnt4n** [zeit/now-desktop#310]
Allowing people to have the choice to disable auto open would be great.

**Comment by leo** [comment]
Fixed in 0fd8aece38f33f1716ae4ef9518caa154e450a01

**Comment by bnjmnt4n** [comment]
Not sure if you understood, but currently now auto launches itself on startup. I would like to disable that behaviour, not prevent the window from opening, which appears to be what your fix does.

**Comment by leo** [comment]
I see
