### ISSUE TITLE
Stuck loading events

### ISSUE THREAD

**Issue by timneutkens** [zeit/now-desktop#311]
Might be just my case. But I had the previous version. It auto-updated. And then got stuck loading them:

![screen shot 2017-07-05 at 21 11 11](https://user-images.githubusercontent.com/6324199/27880831-b8234190-61c6-11e7-9bc7-1c1db857187b.png)

**Comment by leo** [comment]
Thanks @timneutkens - but we're already on it. The platform is experiencing a lot of load from the update we just triggered... 😊

**Comment by timneutkens** [comment]
@leo ❤️
