### ISSUE TITLE
Now creates thousands of 'ShipIt' folders consuming hundreds of GB of disk space

### ISSUE THREAD

**Issue by justsee** [zeit/now-desktop#327]
```
HW: MBP Pro mid-2012
OS: Sierra 10.12.5
Now desktop: 1.3.3
Now cli: 7.2.4
```

My 1TB disk started running out of space with a huge system folder, and after investigating  there were thousands of folders created in `/private/var/folders/_4/${RANDOM_STRING}/T/` in the format `co.zeit.now.ShipIt.${RANDOM_STRING}` weighing in at ~150MB each.

I've removed these, realised I was running an old desktop version (`1.3.3`) and just installed the latest to see whether this situation is resolved.

However as I didn't see this issue listed in Github I wanted to see whether this was a known / fixed issue by the dev team?

**Comment by leo** [comment]
Is it still occurring on the latest Now Desktop version that you downloaded? Because sadly, we can't directly influence this as these files are created by electron's auto updating mechanism automatically after an update was detected and downloaded.

**Comment by justsee** [comment]
@leo ah okay an Electron issue then  with earlier builds - latest Now Desktop doesn't appear to be creating any issues.
