### ISSUE TITLE
Issues with installation on windows

### ISSUE THREAD

**Issue by zusamann** [zeit/now-desktop#330]
I just tried installing the latest release on windows 10. At first it threw an error during installation.
![image](https://user-images.githubusercontent.com/12589797/28301975-256ab9b4-6ba8-11e7-9722-990422163177.png)

 And post installation the app itself appears completely blank. 

Tried opening the only other available screen `about` which is also blank. Here is a screen shot of them on top of each other.

![image](https://user-images.githubusercontent.com/12589797/28301930-d6bf7c50-6ba7-11e7-9e1e-677b766f0afd.png)

**Comment by zusamann** [comment]
After that I tried installing 2.2.0 and it threw this error while installation.
![image](https://user-images.githubusercontent.com/12589797/28302006-57cbba84-6ba8-11e7-9d9f-fb7417c8e36f.png)

**Comment by zusamann** [comment]
Same error with 2.1.0 
![image](https://user-images.githubusercontent.com/12589797/28302165-61bc729e-6ba9-11e7-9d87-516a3d59ee85.png)

**Comment by zusamann** [comment]
I do have a few electron based applications like Slack, VSCode, Hyper & Insomnia installed. And all of them work perfectly fine. So not sure if it's something to do with my system.

In any case would be happy to help resolve this matter.

**Comment by zusamann** [comment]
Next I tried the `now-cli` and it too is failing to work. 😭
```
myDir $ npm i -g now
C:\Users\xxxxxxx\AppData\Roaming\npm\now -> C:\Users\xxxxxxx\AppData\Roaming\npm\node_modules\now\download\dist\now

> now@7.2.4 postinstall C:\Users\xxxxxxxPareek\AppData\Roaming\npm\node_modules\now
> node download/install.js

> For the source code, check out: https://github.com/zeit/now-cli

> Downloading now CLI 7.2.4 [====================] 100%

updated 1 package in 90.289s
myDir $ now
/c/Users/xxxxxxx/AppData/Roaming/npm/now: line 1: /node_modules/now/download/dist/now: No such file or directory
```

**Comment by leo** [comment]
Which version of windows are you using? Also: Which kinda of command line setup are you using? Bash on windows?

**Comment by zusamann** [comment]
I'm using Windows 10 Pro. As for the `now-cli` failure I looked at the relevant issue here https://github.com/zeit/now-cli/issues/613 and it seems it's due to my set up of `git bash` and it will be resolved when released.

But for the `now-desktop` I suppose the command line setup wouldn't be important.

**Comment by leo** [comment]
@zusamann Is it still not working with the latest version?

**Comment by leo** [comment]
Fixed with this: https://github.com/zeit/now-desktop/pull/328

**Comment by bennygenel** [comment]
I'm having a black window on Windows 10 still with version 2.3.3

![screen](https://user-images.githubusercontent.com/4287862/29270295-cbb97394-80fe-11e7-9051-82965e67ca48.jpg)
