### ISSUE TITLE
Now.app files taking TONS of hard drive space

### ISSUE THREAD

**Issue by lodalo** [zeit/now-desktop#331]
I am trying to remove now.app since it crashes when I try to open it. I can't see docs related to the complete removal. :-(

I ~~have~~ had a ton of files in the folder:
/private/var/folders/94/706dbty57cd5nskwyvx7l3dr0000xp/T
(I found the files doing a scan to determine what is taking so much space in my drive.)

Which looked like:
co.zeit.now.ShipIt.zyCaY5XT
co.zeit.now.ShipIt.zAp0ezms
etc.....

**They were taking almost 60Gb!!!!!**

I have used "Now" no more than 5 times with some small sample projects. _Where is all that stuff coming from!!?_

--------------
**BEFORE removal** $ df -h
Filesystem      Size   Used  **Avail** Capacity iused      ifree %iused  Mounted on
/dev/disk1     465Gi  462Gi  **2.6Gi**   100% 4891709 4290075570    0%   /

**AFTER $ rm -Rf co.zeit.now.ShipIt.&ast;**
$ df -h
Filesystem      Size   Used  **Avail** Capacity iused      ifree %iused  Mounted on
/dev/disk1     465Gi  404Gi   **61Gi**    87% 2991236 4291976043    0%   /

---------------------
I initially left this comment on another issue (#219), but I realized it was closed... so I am creating a new issue.

**Comment by leo** [comment]
That's very weird! I sadly have no idea how to fix this. It seems to be an issue with [Electron](http://electron.atom.io), not with our project. Hmmm...

**Comment by lodalo** [comment]
I was about to delete the logs as well, but could upload them if you think that would be useful.

**Comment by lodalo** [comment]
Something weird is going on with now desktop. I had to restart my computer and when the system came back up, now was automatically loaded (which I had set in the preferences). Immediately it started creating those folders again!!!!!

`lodalo-mobile /private/var/folders/94/706dbty57cd5nskwyvx7l3dr0000gp/T$ ls -d co.zeit* | wc
     215     215    6020
lodalo-mobile /private/var/folders/94/706dbty57cd5nskwyvx7l3dr0000gp/T$ date; ls -d co.zeit* | wc
Fri Jul 28 15:13:45 EDT 2017
     216     216    6048
lodalo-mobile /private/var/folders/94/706dbty57cd5nskwyvx7l3dr0000gp/T$ date; ls -d co.zeit* | wc
Fri Jul 28 15:13:56 EDT 2017
     216     216    6048
lodalo-mobile /private/var/folders/94/706dbty57cd5nskwyvx7l3dr0000gp/T$ date; ls -d co.zeit* | wc
Fri Jul 28 15:14:06 EDT 2017
     221     221    6188
lodalo-mobile /private/var/folders/94/706dbty57cd5nskwyvx7l3dr0000gp/T$ date; ls -d co.zeit* | wc
Fri Jul 28 15:14:20 EDT 2017
     222     222    6216
lodalo-mobile /private/var/folders/94/706dbty57cd5nskwyvx7l3dr0000gp/T$ date; ls -d co.zeit* | wc
Fri Jul 28 15:14:46 EDT 2017
     228     228    6384
lodalo-mobile /private/var/folders/94/706dbty57cd5nskwyvx7l3dr0000gp/T$ date; ls -d co.zeit* | wc
Fri Jul 28 15:15:41 EDT 2017
     239     239    6692`

**Comment by leo** [comment]
@lodalo Which logs are you talking about? Can you send them to me on [zeit.chat](https://zeit.chat) if they contain sensitive data? If not, just post them here.

**Comment by leo** [comment]
We're working on a solution!

**Comment by leo** [comment]
Will be fixed with [this](https://github.com/zeit/now-desktop/issues/335). 😊
