### ISSUE TITLE
Show reason for logging a user out/prompting for a login

### ISSUE THREAD

**Issue by Qix-** [zeit/now-desktop#355]
If you have the Now desktop client running and remove any of the configuration files, Now will (correctly) prompt you to login again.

However, the reasoning for it isn't immediately clear, and in the event it's _unexpected_, it could be frustrating to be interrupted - especially if there's a rogue script removing the configuration over and over for some reason.

We should include a logout reason and/or notification for being logged out whenever these types of things occur.

There is currently the `logout` function that takes no arguments. However, I think it should take at least a `reason` argument that is displayed to the user.

Further, I don't know that we should immediately pop up the window for logging in again since the missing configuration could be temporary - many users choose to mount their home directory on some external media that may become temporarily unavailable from time to time.

If/when this is fixed, we should make sure the fix accounts for boot-ups - that is, the login window _should_ automatically display if the configuration is missing upon starting up Now Desktop.

**Comment by leo** [comment]
This sounds like a good idea, as explained above:

```js
configFile.on('unlink', () => logout({reason: 'config-unlink'}))
```

**Comment by Qix-** [comment]
🎉 Better than I had hoped. Good job @leo

**Comment by leo** [comment]
@Qix- Thaaanks! ❤️
