### ISSUE TITLE
"Open at login" non-togglable

### ISSUE THREAD

**Issue by Meadowcottage** [zeit/now-desktop#358]
Now Version: 2.5.0
MacOS version: 10.13 Beta

When trying to toggle the `Open at login` option in the dropdown menu, clicking on it performs no action.
See below for example:

![2017-09-10 23 44 24](https://user-images.githubusercontent.com/4991309/30253693-43830fe6-9682-11e7-8d99-ea0ef54c414e.gif)

**Comment by leo** [comment]
Can you check the "User & Groups > Login items" section for Now? 😊

**Comment by Meadowcottage** [comment]
Ah yeah. Seems it was still being stored as a login item there.
Removed it from there any it fixed it.

**Comment by leo** [comment]
Sweet 😊
