### ISSUE TITLE
Main popover window is placed under the menu bar on macOS

### ISSUE THREAD

**Issue by sindresorhus** [zeit/now-desktop#370]
When the menu bar is set to be auto-hidden in the system preferences.

<img width="384" alt="screen shot 2017-09-17 at 14 20 05" src="https://user-images.githubusercontent.com/170270/30518867-5eb2fdc2-9bb3-11e7-82dc-119a9f2cc349.png">

The solution is to use [`screen.getMenuBarHeight()`](https://electron.atom.io/docs/api/screen/#screengetmenubarheight-macos) to get the menu bar height. It will be `0` when the menu bar is hidden and 22 when it's shown.

**Comment by leo** [comment]
@sindresorhus Thanks for the suggestion. But how exactly should we implement that? I mean, is the problem that the app doesn't move down when the menu bar slides down? Or is it that the app appears below the menu bar when its launched?

**Comment by sindresorhus** [comment]
> Or is it that the app appears below the menu bar when its launched?

Yes

**Comment by PerStirpes** [comment]
Is the app suppose to float when the cursor is moved away from the menubar? Is that correct? 
- env: Automatically hide and show the menu bar is checked 
- Left: reproduced
- Right: Blue Caret verticalPosition += 22
![verticalheighgt](https://user-images.githubusercontent.com/19398470/31053378-aaef8a1e-a650-11e7-8895-5f7266dfa752.gif)


So is the fix simply this
```js
    if(screen.getMenuBarHeight() === 0){
       verticalPosition += 22;
    }
```
right under line 49?
https://github.com/zeit/now-desktop/blob/b8713f797542b9cfca6e753c68b6c50df6df300a/main/utils/frames/position.js#L49

**Comment by sindresorhus** [comment]
@PerStirpes In my opinion, yes.

**Comment by PerStirpes** [comment]
Okay, I'll submit the pr over this weekend
