### ISSUE TITLE
Now Desktop only available for macOS

### ISSUE THREAD

**Issue by fgallardograzio** [zeit/now-desktop#374]
In https://zeit.co/download there's only one download link for Now Desktop, and that's for macOS.
I'm currently on Linux Mint 18.

I assume this is a bug since in the [installation instructions](https://zeit.co/docs/getting-started/installation) it's stated that:
>This is a desktop app which is available for all of the major operation systems. It comes as an operation<strong>*</strong> system status bar app.

And then it's mentioned that the app is powered by Electron, so it should be multi-platform indeed.

*: Yeah, it says "operation system", you should fix that as well.

**Comment by leo** [comment]
It also works on Windows! 😊

When accessing the site on Windows, it will provide the appropriate download.

A linux version is coming!
