### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by akshaynanavati** [zeit/now-desktop#378]
How do I fully uninstall the now desktop client (including all files it has created)?

**Comment by PerStirpes** [comment]
Not an official way but you can use [AppCleaner]( https://freemacsoft.net/appcleaner/). It'll do the trick by removing the small files spread around your hard drive. Probably not an ideal situation to download another app to get rid of an app but it will work.

**Comment by leo** [comment]
I suggest using the application mentioned above, if you truly want to remove everything 😊

**Comment by leo** [comment]
@akshaynanavati Would you like to tell us why you want to remove the application? Are you somehow unhappy with it? 😊

**Comment by scotttesler** [comment]
@leo I want to uninstall it as well. I don't find it useful; I only need the CLI.

Are there official instructions on removing the desktop app?

**Comment by MrPotatoLord** [comment]
You can try uninstalling everything and then installing the cli version, or on windows if you remove it from programs the cli version wouldn’t get removed (probqbly a bug though)

**Comment by ogryzek** [comment]
```
rm -rf $(which now)
```

**Comment by DezChuang** [comment]
I had the same question too, and I remove it successfully by the command below,

```
rm -rf /Applications/Now.app/
```

**Comment by ariestav** [comment]
I'd like to uninstall because the "Start on Login" option does not work.  No matter what I do, it always starts upon login and I don't need it when I login all the time.  From time to time I see the menu appear from the triangle icon for no apparent reason and it's kind of bothersome when I'm trying to do work.  Yes, it just shows up.

**Comment by coolcomfort** [comment]
Is there really not a way to uninstall this application within the app? You are making us use a third party app like AppCleaner to remove this? I will never consider using this app, or even recommending it to a friend.

**Comment by leerob** [comment]
As mentioned above, there are two ways to uninstall.

1. [AppCleaner](https://freemacsoft.net/appcleaner/)
2. `rm -rf $(which now)` or `rm -rf /Applications/Now.app/`

Thanks!
