### ISSUE TITLE
Fails to move to Applications folder itself in High Sierra

### ISSUE THREAD

**Issue by bodaz** [zeit/now-desktop#381]
Software: macOS Version: 10.13 (High Sierra)
Hardware: MacBook Air (13-inch, Early 2015)
Zeit Now version: 2.6.0

Desktop app fails to move itself to the Applications folder, and after manually moved to the Applications folder the app fails to launch. The only way I got the app running is just to launch it from the downloads folder.

**Comment by PerStirpes** [comment]
This may help https://github.com/zeit/now-desktop/issues/208.

If not, did you download it using Brew or from https://zeit.co/download? I assume the latter.

If downloaded from https://zeit.co/download, do you have the radio button for 'App Store and identified developers' selected under System Preferences > Security & Privacy? 

![security___privacy](https://user-images.githubusercontent.com/19398470/31061149-cc02dd00-a6d2-11e7-84b1-1ccda7d0ed59.png)

**Comment by bodaz** [comment]
The setting's the same in the Security & Privacy. After I launched the app from Downloads folder, I quit the app, manually moved it to Applications and it's working fine now.
