### ISSUE TITLE
Suggestion/feature request: Remove multiple deployments

### ISSUE THREAD

**Issue by bestwestern** [zeit/now-desktop#385]
Hello
It takes very long to tidy up (removing old deployments) using the CLI.
Could you please make it possible to select multiple deployments in the now-desktop (or online dashboard!) and then delete them?

**Comment by leo** [comment]
@bestwestern Have you tried `now rm <app-name> --safe` which removes all deployments of a name, except for those that are aliased? Also, just by the way: There's no advantage in removing deployments, you can just leave them laying around... 😊

**Comment by bestwestern** [comment]
thx @leo ! nice with the command that deletes many.
I could image a scenario where I had sent a link with a version with a new feature to some users, but changed the data model so the new feature would break it I would want to make sure the old one was no more :)
