### ISSUE TITLE
Improved CLI installation flow

### ISSUE THREAD

**Issue by rauchg** [zeit/now-desktop#390]
![image](https://user-images.githubusercontent.com/13041/32418379-7a548998-c21d-11e7-8713-16e8988a92ad.png)

This approach has numerous benefits:
- It starts downloading the CLI on the background, optimistically
- It skips the "call to action" button to install the CLI
- It skips an entire additional pane
- It's clear about (potentially) needing administrator permissions, which makes the user not be surprised about a password dialog popping up

We can communicate success of the installation of the CLI just like we do any update. In fact, the installation itself starts working like an update. Meaning that if I log in, quit the application (without the download nor installation finishing), it will be seamlessly retried in the future.

**Comment by melvin0008** [comment]
I would like to work on this. Is it open for developers to contribute?

**Comment by rauchg** [comment]
@melvin0008 absolutely! Very high impact task IMO!

**Comment by melvin0008** [comment]
What is the expected result when the silent download fails? Should it retry? Fail silently ? Notify user of the failure?

**Comment by amio** [comment]
Could user trigger download manually?

**Comment by rauchg** [comment]
> What is the expected result when the silent download fails? Should it retry? Fail silently ? Notify user of the failure?

The way to think of this is that the initial download is the same as an _update from version 0.0.0_. The same logic as updating would follow, it would retry later.

If the version is "0.0.0", I would probably retry with a smaller interval.

It would also be nice to use the new electron first-class notifications to notify the user that "There was a problem installing the Now CLI. We will retry automatically". Maybe @leo wants to weigh on the error conveyance approach however.

> Also, should the download start when this component is mounted or should it download after the user verifies himself?

I think it should start downloading right away. Ideally we could also halt the download if the user checks out the box.

**Comment by melvin0008** [comment]
@rauchg 

> I think it should start downloading right away. Ideally we could also halt the download if the user checks out the box.

I made this happen but if the download finishes earlier than the user clicking the checkbox and the user doesn't get time to choose. Should I add a timeout? Should I delete the package once the user unchecks it? 

I feel we should download it after the user verifies himself.

**Comment by rauchg** [comment]
The download would happen to a temporary location. No need to wait.

**Comment by melvin0008** [comment]
> The download would happen to a temporary location (eg: /tmp, a.k.a os.tmpdir()). No need to wait.
The download would take place to the temp directory and once its over it will be moved to the destination.

My question was what is expected when the user unchecks the box after the binary is in its destination.

If we defer the movement of the binary to the destination, when should this movement take place?

**Comment by leo** [comment]
It should go like this:

1. User opens Now Desktop for the first time, the binary gets pre-fetched and saved into a temporary directory (no need to write any of this, the logic is already there)
2. If the user completes the login/signup with the box checked, the methods for adding the binary to the path (only on Windows, on macOS the directory that gets chosen is already in the path) should be called. If the user completes the login/signup without the box checked, we delete the tmp dir.
3. 🎉

**Comment by melvin0008** [comment]
Thanks for the clarification. I will get this done today.

**Comment by leo** [comment]
✅
