### ISSUE TITLE
Avast - The false alarm

### ISSUE THREAD

**Issue by rufatmammadli** [zeit/now-desktop#416]
As you can see from the below, the **Avast Antivirus** detects a potential threat called Evo-gen. It should be reported to Avast as a **false alarm**.

![image](https://user-images.githubusercontent.com/5330471/32805676-9374969c-c9a3-11e7-8f9e-434c1ff35d47.png)

**Comment by leo** [comment]
<img width="1046" alt="screen shot 2017-11-20 at 12 08 23" src="https://user-images.githubusercontent.com/6170607/33015570-85633490-cdeb-11e7-91ef-c2923cc7be73.png">

Reported it. Thanks!
