### ISSUE TITLE
Hard Disk out of space

### ISSUE THREAD

**Issue by Ferrari** [zeit/now-desktop#417]
Just found my HD always got out of space after I start working couple hours later, and found that seem now-desktop keep writing data, not sure the root cause. But after I stop now-desktop everything back to normal. (Same issue as #331, but I thought the issue already been solved?)

![image](https://user-images.githubusercontent.com/173408/33000128-29e1bde4-cde1-11e7-9b84-4a89f81b459b.png)
![image](https://user-images.githubusercontent.com/173408/33000131-2eafff3e-cde1-11e7-9434-7c09863d7277.png)

**Comment by melvin0008** [comment]
Do you have now-cli installed? You can check that by typing now in your terminal.

**Comment by okuryu** [comment]
I have the same issue. now-cli isn't installed.

**Comment by vjpr** [comment]
I think I saw that the temp entries were cleaned up after `now-desktop` was closed.

I think its the retry logic or maybe failing to extract triggers a new download.

**Comment by stoutZero** [comment]
On my disk, now's temp dir was 25GB.

![single file](https://i.imgur.com/y91UoG3.png)

![temp dir](https://i.imgur.com/PA0AJsw.png)

After I quit now-desktop, that folder was cleaned, but only after quiting... 😢

**Comment by Ferrari** [comment]
> Do you have now-cli installed? You can check that by typing now in your terminal.
Yes, 8.5.1

**Comment by melvin0008** [comment]
@leo  Looking into it

**Comment by leo** [comment]
@melvin0008 I think I found it. Opening a PR!
