### ISSUE TITLE
CLI is not on path

### ISSUE THREAD

**Issue by SteveALee** [zeit/now-desktop#423]
I installed the desktop but the despite what https://zeit.co/blog/automatic-cli-installation says the cli is never available. I even rebooted. 

When I installed it I was already logged in via a local project install. Is this an edge case? How do I get the CLI to be put on my path? 

For now I'll go back to adding to my project dependencies and launching it with npx

I'm on WIndows 10

**Comment by melvin0008** [comment]
@SteveALee One way to get around this is to toggle the Auto-Update Now Cli preference.
Also, what do you mean by a local project install? Do you mean installing this git repository?

@leo Do we expect every user to go through the login flow?

**Comment by SteveALee** [comment]
@melvin0008 ill try that, thanks. Yes by local I mean project not global. I always try to ensure ALL deps are in package.json so is full self documenting

**Comment by SteveALee** [comment]
Ps i assume that is the reason I did not need to login.

**Comment by SteveALee** [comment]
I confirm  "toggle the Auto-Update Now" worked. Thanks for closing!
