### ISSUE TITLE
Reverse option order on Windows

### ISSUE THREAD

**Issue by leo** [zeit/now-desktop#425]
This doesn't look good, so let's put "OK" up and "Please, no!" down:

<img width="649" alt="screen shot 2017-12-18 at 03 00 25" src="https://user-images.githubusercontent.com/6170607/34103310-9c561854-e3ec-11e7-8453-0dcdb7215777.png">

Let's also change the text for "Please, no!" 😊

**Comment by timneutkens** [comment]
It's also strange that `Please, no!` has an exclamation mark

**Comment by leo** [comment]
@timneutkens That's what I meant with:

> Let's also change the text for "Please, no!"

We'll change it to something more like "Cancel" 👍

**Comment by timneutkens** [comment]
Ah, missed that bit 😄 👌
