### ISSUE TITLE
Using multiple displays will cause menu bar popup to open in the wrong location 

### ISSUE THREAD

**Issue by maxxafari** [zeit/now-desktop#450]
Clicking  the now icon in the menubar on the second display will cause the popup to on the wrong location on the x-axis.
I guess it because the displays have different resolutions. The external monitor is a 28" 4k and the other is the built in display on the macbook pro 15".

<img width="1098" alt="screen shot 2018-02-27 at 09 10 59" src="https://user-images.githubusercontent.com/7019830/36717394-34564a00-1b9e-11e8-9eaa-fe757a902d5b.png">

**Comment by leo** [comment]
Seems to be fixed with the latest release!

@maxxafari Please us know if you're experiencing any other issues! 😊
