### ISSUE TITLE
Request: Retain original URL

### ISSUE THREAD

**Issue by KBPsystem777** [zeit/now-desktop#452]
Hi there! Not sure if this has been addressed already, see example:

- I originally deployed `app-X` After that I got a URL of `https://now.app-x.com`
- Need to add new file to `app-X` After saving the changes, I redeployed it on Now server. After this step I got a new URL of `https://now.app-x1234.com`

Is it possible to retain the `https://now.app-x.com` even after adding or removing files and deploying them?

Thanks

**Comment by leo** [comment]
Each deployment is immutable on Now. If you want the URL to stay the same, you need to alias the deployment after you've created it ([like this](https://zeit.co/docs/features/aliases)).
