### ISSUE TITLE
Linux (ubuntu) version ?

### ISSUE THREAD

**Issue by Bigg-Mike** [zeit/now-desktop#458]
Hi,

is there a linux version for now-desktop?

Thanks

**Comment by leo** [comment]
No yet, but we're working on it! 😊

**Comment by Flo-Slv** [comment]
Hello here !

Any news about linux version?

**Comment by HINW** [comment]
Any news about linux version?

**Comment by rodislav** [comment]
no news so far :) I'm always amazed seing monoplatform apps built with crossplatform technologies :D

**Comment by usama-asfar** [comment]
thumbs up if your waiting for Now-Desktop for ubuntu
