### ISSUE TITLE
Support Dark Mode on macOS

### ISSUE THREAD

**Issue by pranaygp** [zeit/now-desktop#485]
Apple announced Dark Mode for macOS on the next release and electron already has an API to detect when we're in dark mode. It would be awesome to support dark mode, and we should also have a preference that lets you pick Dark Mode (overriding system default).

cc: @evilrabbit

**Comment by timothyis** [comment]
@MAPESO That's too much of a nuisance for installing Now Desktop. That would be the _only_ prompt before launching the entire app and it's not even the core functionality we're offering. 
This should work by following the system initially and offering a toggle to change it in the preferences.

**Comment by rauchg** [comment]
It wouldn't be the only prompt, since we have the onboarding / login screen. It could be fit there, but not sure if necessary.

**Comment by MAPESO** [comment]
@rauchg I could work on implementing it, having a dark mode would be great 😄

**Comment by leo** [comment]
This is done
