### ISSUE TITLE
Error deploying now-examples/wordpress  

### ISSUE THREAD

**Issue by chenraz** [zeit/now-desktop#522]
I am trying to deploy a wordpress installation from you official example:

https://github.com/now-examples/wordpress

I am getting an error:
The built image size (215.0M) exceeds the 100MiB limit
(I have the Pro plan)

https://zeit.co/tilnet/wordpress/wvailnbbfr?redirect=1

Does is mean that it is impossible to deploy wordpress to Now, or am I missing something else?

**Comment by joecohens** [comment]
Hi @chenraz, yes it is possible to deploy Wordpress to Now 😄we have a new repository for all the examples updated, it lives on: https://github.com/zeit/now-examples I will also leave you here the Wordpress one https://github.com/zeit/now-examples/tree/master/php-wordpress

**Comment by chenraz** [comment]
Thanks for the link.

I cloned https://github.com/zeit/now-examples to my desktop.
Then I upload now-examples/php-wordpress folder to Now, using the Now windows desktop client.
 
I am getting this error:

/usr/local/bin/docker-php-entrypoint: exec: line 9: ./run.sh: not found

https://zeit.co/tilnet/php-wordpress/xnvatemrig?redirect=1

What could I be doing wrong?
