### ISSUE TITLE
Javascript Error in main process for desktop zeit

### ISSUE THREAD

**Issue by codebender828** [zeit/now-desktop#579]
Zeit Desktop Service is not launching after last update.

**Operating System**
macOS Mojave 10.14

**Steps to reproduce:**
Launch Desktop Application

<img width="485" alt="screen shot 2018-12-17 at 8 51 54 pm" src="https://user-images.githubusercontent.com/21237954/50088734-cf42cc00-023e-11e9-8466-42c4f0678088.png">

**Comment by alexperetti** [comment]
Getting the same thing. On macOS Mojave 10.14 too.
Tried deleting Library/Application Support/Now and the Preferences + reboot but still doesn't work.

Now desktop version is 4.0.16 which seems to have been released today.

**Comment by paulogdm** [comment]
Hello! We just issued a fix and it will arrive shortly. https://github.com/zeit/now-desktop/pull/580
