### ISSUE TITLE
Desktop opening itself over and over again

### ISSUE THREAD

**Issue by jimmyhmiller** [zeit/now-desktop#581]
The now desktop app and the now helper kept opening themselves seemingly endlessly. Trying to kill them with `killall Now` said something about fork not being available. Sadly computer was too frozen to capture the actual message. A restart fixed the issue. 

It seems this had happened [more than a year ago](https://github.com/zeit/now-desktop/issues/290), but these are entirely different versions, so I am opening this issue. I am using version 4.0.17. It says next the the version (2 hours) if that means how long I've had the version, it could be an update the caused the issue?

Here is a screenshot of what my menu bar looked like when this happened.

<img width="1920" alt="screen shot 2018-12-17 at 10 22 47 am" src="https://user-images.githubusercontent.com/6071338/50097214-5f552700-01e7-11e9-8d14-1f4c49d4a15d.png">

If there is other info I can provide, let me know.

**Comment by apnerve** [comment]
Happened to me just now. Had to restart my mac

**Comment by jimmyhmiller** [comment]
Just FYI this started happening again, but I caught it before it went out of control.

**Comment by mattborn** [comment]
This just happened to me as well. Dozens of app instances and hundreds of helper instances in Activity Monitor and also maxed out my CPUs. Was able to kill it without restart, but never seen anything like this before.

**Comment by fschroiff** [comment]
![screenshot 2018-12-18 at 08 56 21](https://user-images.githubusercontent.com/660010/50140312-99d0c980-02a4-11e9-8d3d-a5ac342d09eb.png)

Yes, me too! macOS 10.14.2 (18C54)

**Comment by origamium** [comment]
Yeah, now now now now now... and now open!(macOS 10.14.1) after forced restart, isn't occurred(for now). 
<img width="977" alt="screen shot 2018-12-18 at 19 57 03" src="https://user-images.githubusercontent.com/5967271/50150035-2a88c300-0300-11e9-9ef1-f71768b15ea6.png">
 
<img width="815" alt="screen shot 2018-12-18 at 19 58 01" src="https://user-images.githubusercontent.com/5967271/50150022-1d6bd400-0300-11e9-8a89-2a3a797e6a8d.png">

**Comment by fschroiff** [comment]
I received an email from ZEIT: 

> Due to a bug in the auto-update handling library invoked by Now Desktop, some users of the application might currently be experiencing errors or crashes. Not every installation is affected.
> 
> If you are impacted by this bug, the only way to regain access to the application is, unfortunately, a reinstallation. This only impacts your local installation. Your live data and deployments are safe and unaffected.

So: 
1. trash the app
2. reinstall from a fresh [download](https://zeit.co/download) (alternatively `brew cask reinstall now`)

**Comment by Korkman** [comment]
Happened to me now on windows with 4.0.15

**Comment by leo** [comment]
This unfortunately happened due to the bug mentioned in the email.

Please re-install Now Desktop.
