### ISSUE TITLE
Now menubar not responding

### ISSUE THREAD

**Issue by mvllow** [zeit/now-desktop#593]
Every once in a while I will be hovering near the Now Desktop menubar icon (macOS) and it will show the spinning rainbow. After closing Now via Activity Monitor it quickly starts back up and works as expected. Running Mojave and have reset my computer since the issue and it still persists after a fresh install. Tried canary releases as well as stable. If there is anything else I can do let me know! Thanks!

**Comment by MAPESO** [comment]
@mvllow Hi, this is a problem that has happened to me, but unfortunately there is no way to intentionally reproduce it 🙍 

This is a problem that has happened to me, but unfortunately there is no way to intentionally reproduce it.

**Comment by mvllow** [comment]
Closing as I haven't experienced this since either a system update (Mojave betas) or Now canary update.

**Comment by hubgit** [comment]
I experience this quite frequently (maybe once every couple of weeks), including just now (v4.0.19). 

It's possible it might be connected to CLI auto-updates, but that might be a coincidence.

**Comment by mvllow** [comment]
Happened again after our internet cycled off for a second.

**Comment by SamuAlfageme** [comment]
Noticed quite a few times already. I took a hanging process sample in case it can be of any help: https://gist.github.com/SamuAlfageme/96f10b25cd75058ced1042a4ebf9a9ba
