### ISSUE TITLE
Stuck at email verification step

### ISSUE THREAD

**Issue by WickyNilliams** [zeit/now-desktop#601]
Seems to be similar issue as described in #302.

I enter my email address, email is sent, open email, click link, see page confirming email address. However the desktop app itself is stuck waiting to receive the confirmation.

Opening the dev tools and taking a look at what's going on, I'm getting 403 response when verifying email:

```json
{
  "error": {
    "code": "forbidden",
    "message": "Invalid verification token"
  }
}
```

Any idea why this might be? I cannot progress with the setup as a result.

_Sidenote: copy and paste seems to be broken in the dev tools (on Mac)_

**Comment by WickyNilliams** [comment]
When I try to use the CLI for the first time (installed via npm, since I couldn't progress with the desktop app), I get this message:

```sh
$ now
> No existing credentials found. Please log in:
> Enter your email: xxxxxxx@gmail.com
> Error! Your email address is invalid. Please try a different email provider or GitHub sign up, or email us at support@zeit.co for help.
```

**Comment by WickyNilliams** [comment]
This may be due to a misunderstanding on my part as I have a token which was provided to me, so perhaps I don't need to login with email at CLI? The question about the desktop app remains, however.

**Comment by MAPESO** [comment]
@WickyNilliams  That mistake has also happened to me. the only thing I could recommend is that you delete the application and reinstall it 😢

**Comment by cr101** [comment]
I confirm that I have the same problem as @WickyNilliams in that the desktop app is stuck waiting to receive the confirmation.
![screenshot_1](https://user-images.githubusercontent.com/4064582/53133882-befdf300-35d9-11e9-93eb-b952cf848455.jpg)

**Comment by wunnle** [comment]
This is happening to me also both on now-desktop and now-cli. Reinstalling does not solve the issue and it's impossible to log in

**Comment by fengxiaoyue** [comment]
+1

**Comment by ArashiAozora** [comment]
I have the same problem

**Comment by Bianca-NL** [comment]
Same issue here

**Comment by leo** [comment]
This problem is now fixed in the latest version. It was due to the email not being correctly validated.

Now you will see an error if you're trying to use a invalid email.

**Comment by cr101** [comment]
It's interesting that I can't use a gmail address

**Comment by Painmbox** [comment]
I have the same issue.

**Comment by BlazFin** [comment]
Having same issue using 3 different emails. 
Your email address is invalid. Please try a different email provider or GitHub sign up, or email us at support@zeit.co for help.
Version: + now@15.0.2

**Comment by NICK-DUAN** [comment]
+1

**Comment by Rapol** [comment]
I had the same problem, tried two different domains. The problem was that I had not fully registered with zeit (https://zeit.co/login). Sign up with github (if you want, you can skip the github repo integration) and then run `now login` with the same email you have set up in github.

The underlying problem is that the error message is confusing. Should say something like:
`Your email address is invalid or is not registered. Please register at https://zeit.co`

**Comment by jantonioavalos** [comment]
Same problem. Terminal keeps waiting for confirmation. 
I get the email, click at Verify...
And browser tab keeps saying "Verifying". But nothing happens.

(I'm using the same email that I used at my Vercel profile)
