### ISSUE TITLE
A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by Ugarz** [zeit/now-desktop#603]
Hi there, I'll try to be as clearest as possible.
## Goal
Launch the app and process `now-cli` in iTerm2.

## Context
Launching my computer this morning. Now app is launching on start up.

## Issue
This morning it is impossible to me to launch / use the now-cli. `A Javascript error occurred in the main process` according to this screenshot.

**I can not delete the app nor kill it.**

It says
```
pkg.includes is not a function
```
<img width="532" alt="capture d ecran 2018-12-18 a 09 50 01" src="https://user-images.githubusercontent.com/6050079/50143308-93dee680-02ac-11e9-86fc-6f34ec5ddc8c.png">

I'm currently using mac Mojave v10.14.2 and did not had this issue last week. I have `nvm` installed and v10.0.0 lts as default.
Thanks for reading !

**Comment by juliangruber** [comment]
This has been fixed in recent updates to Now Desktop 🎆
