### ISSUE TITLE
Deleting a team while it is the active scope will break

### ISSUE THREAD

**Issue by leo** [zeit/now-desktop#618]

**Comment by karaggeorge** [comment]
Tried to work on this, but latest `canary` seemed to handle the deletion of a team just fine. Is there any more info around what breaks? If so, I can work on it

**Comment by leo** [comment]
@karaggeorge Did you check if the team is the active scope? Before it gets deleted.

**Comment by karaggeorge** [comment]
@leo when you say active scope you mean selected in the now-desktop app right? I had it selected, deleted the team, opened the app and after clicking around it removed that team, without any errors

**Comment by leo** [comment]
@karaggeorge Right. What I mean is the app needs to be open while you're deleting it. You can achieve that by opening the developer inspector. 🙂

**Comment by rdev** [comment]
Closing as this doesn't happen in the latest canary
