### ISSUE TITLE
Problem with the updates

### ISSUE THREAD

**Issue by MAPESO** [zeit/now-desktop#621]
**OS:** macOS Mojave (10.14.4)
**now desktop:** 5.0.0-canary.1

The expected behavior would be to get the **latest canary version of now cli** but I am getting 
the latest stable version of now cli 😕 

<img width="358" alt="Screen Shot 2019-04-17 at 14 45 44" src="https://user-images.githubusercontent.com/16585386/56317444-60a94880-6122-11e9-8ec8-69801b5b910a.png">

```{
  "_": "This is your Now config file. See `now config help`. More: https://git.io/v5ECz",
  "updateChannel": "canary",
  "desktop": {
    "shownTips": {
      "pasteFromClipboard": true
    },
    "updateCLI": true
  }
}

**Comment by leo** [comment]
Fixed in https://github.com/zeit/now-desktop/pull/632
