### ISSUE TITLE
Logging out using the CLI and then running the app breaks

### ISSUE THREAD

**Issue by karaggeorge** [zeit/now-desktop#624]
I quite the app, ran `now logout`, then ran the app again and it got stuck to this:

<img width="352" alt="Screen Shot 2019-05-01 at 3 53 38 PM" src="https://user-images.githubusercontent.com/8822835/57039371-75a9cf80-6c2a-11e9-8e48-725cdf640c0d.png">

(This is on the canary version)

**Comment by leo** [comment]
What version are you running?

**Comment by leo** [comment]
I just tried it with the latest canary and it seems to be working.
