### ISSUE TITLE
Download links gone

### ISSUE THREAD

**Issue by tim-phillips** [zeit/now-desktop#691]
At https://zeit.co/download there is no mention of the desktop app. Should we just use the CLI now?

<img width="993" alt="Screen Shot 2019-08-09 at 9 41 48 AM" src="https://user-images.githubusercontent.com/3578574/62794838-fed26d00-ba89-11e9-82ce-b92b2197dffe.png">

**Comment by leo** [comment]
Indeed! Now CLI is now the recommended way to interact with ZEIT Now.

However, Now Desktop will continue to be maintained and receive security updates.
